# Generated by Django 3.2 on 2023-08-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_cardinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinformation',
            old_name='full_name',
            new_name='email',
        ),
    ]
