# Generated by Django 3.2 on 2023-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20230802_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='vitamin',
            new_name='contextfirst',
        ),
        migrations.AddField(
            model_name='blogs',
            name='contextsecond',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='contextthird',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='titlefirst',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='titlesecond',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='titlethird',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
