# Generated by Django 3.2 on 2023-08-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20230802_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
