# Generated by Django 3.2 on 2023-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20230818_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='contextfourth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='titlefourth',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
