# Generated by Django 3.2 on 2023-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('category', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('oldprice', models.FloatField(max_length=250)),
                ('newprice', models.FloatField(max_length=250)),
                ('calories', models.FloatField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('description_text', models.TextField(max_length=250)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
