# Generated by Django 3.2 on 2023-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='description_text',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='text',
            field=models.TextField(default='', max_length=550),
        ),
    ]
