# Generated by Django 3.2 on 2023-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230728_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='rating',
            field=models.FloatField(default=4.2, max_length=25),
            preserve_default=False,
        ),
    ]
