# Generated by Django 4.2.3 on 2023-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=250)),
                ('addition_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('preparation', models.CharField(max_length=250)),
                ('cooking', models.CharField(max_length=250)),
                ('services', models.CharField(max_length=250)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
