# Generated by Django 3.2 on 2023-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230728_1435'),
        ('api_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.ShopProduct'),
        ),
    ]
